-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS db_jobinsights.tb_usuario
(
    usuario_id bigserial NOT NULL,
    usuario_login character varying(50) NOT NULL,
    usuario_senha character varying(50) NOT NULL,
    usuario_email character varying(50) NOT NULL,
    usuario_nome character varying(100) NOT NULL,
    usuario_confirmacao_email boolean DEFAULT false,
    CONSTRAINT usuario_pk PRIMARY KEY (usuario_id),
    CONSTRAINT uniq_login UNIQUE (usuario_login),
    CONSTRAINT uniq_email UNIQUE (usuario_email)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_aluno
(
    aluno_id bigint NOT NULL,
    aluno_ano_ingresso timestamp,
    cargo_id bigint,
    CONSTRAINT aluno_pk PRIMARY KEY (aluno_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_empresa
(
    empresa_id bigint NOT NULL,
    empresa_descricao text NOT NULL,
    CONSTRAINT empresa_pk PRIMARY KEY (empresa_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_avaliacao
(
    aluno_id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    avaliacao_nota integer NOT NULL,
    avaliacao_titulo character varying(120) NOT NULL,
    avaliacao_pros text NOT NULL,
    avaliacao_contras text NOT NULL,
    CONSTRAINT avaliacao_pk PRIMARY KEY (aluno_id, empresa_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_salario
(
    aluno_id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    salario_valor double precision NOT NULL,
    CONSTRAINT salario_pk PRIMARY KEY (aluno_id, empresa_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_cargo
(
    cargo_id bigserial NOT NULL,
    cargo_nome character varying(50) NOT NULL,
    CONSTRAINT cargo_pk PRIMARY KEY (cargo_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_vaga
(
    vaga_id bigserial NOT NULL,
    vaga_descricao text NOT NULL,
    vaga_salario double precision,
    vaga_tipo integer NOT NULL,
    cargo_id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    CONSTRAINT vaga_pk PRIMARY KEY (vaga_id)
);

CREATE TABLE IF NOT EXISTS db_jobinsights.tb_vagas_aluno
(
    aluno_id bigint NOT NULL,
    vaga_id bigint NOT NULL,
    CONSTRAINT vagas_aluno_pk PRIMARY KEY (aluno_id, vaga_id)
);

ALTER TABLE IF EXISTS db_jobinsights.tb_aluno
    ADD CONSTRAINT fk_aluno_usuario FOREIGN KEY (aluno_id)
    REFERENCES db_jobinsights.tb_usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_aluno
    ADD CONSTRAINT fk_aluno_cargo FOREIGN KEY (cargo_id)
    REFERENCES db_jobinsights.tb_cargo (cargo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_empresa
    ADD CONSTRAINT fk_empresa_usuario FOREIGN KEY (empresa_id)
    REFERENCES db_jobinsights.tb_usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_avaliacao
    ADD CONSTRAINT fk_avaliacao_aluno FOREIGN KEY (aluno_id)
    REFERENCES db_jobinsights.tb_aluno (aluno_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_avaliacao
    ADD CONSTRAINT fk_avaliacao_empresa FOREIGN KEY (empresa_id)
    REFERENCES db_jobinsights.tb_empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_salario
    ADD CONSTRAINT fk_salario_aluno FOREIGN KEY (aluno_id)
    REFERENCES db_jobinsights.tb_aluno (aluno_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_salario
    ADD CONSTRAINT fk_salario_empresa FOREIGN KEY (empresa_id)
    REFERENCES db_jobinsights.tb_empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_vaga
    ADD CONSTRAINT fk_vaga_cargo FOREIGN KEY (cargo_id)
    REFERENCES db_jobinsights.tb_cargo (cargo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS db_jobinsights.tb_vaga
    ADD CONSTRAINT fk_vaga_empresa FOREIGN KEY (empresa_id)
    REFERENCES db_jobinsights.tb_empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
    
ALTER TABLE IF EXISTS db_jobinsights.tb_vagas_aluno
    ADD CONSTRAINT fk_vagas_aluno_aluno FOREIGN KEY (aluno_id)
    REFERENCES db_jobinsights.tb_aluno (aluno_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
    
ALTER TABLE IF EXISTS db_jobinsights.tb_vagas_aluno
    ADD CONSTRAINT fk_vagas_aluno_vaga FOREIGN KEY (vaga_id)
    REFERENCES db_jobinsights.tb_vaga (vaga_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
    
END;